services:
  DataBase:
    image: postgres:17
    container_name: uab-database
    restart: always
    ports:
      - 5222:5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=1844
      - POSTGRES_DB=googlekeep-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
