version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: my-database
    restart: always
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=1844
      - POSTGRES_DB=googlekeep-db
    volumes:
      - ./postgres:/var/lib/postgresql/data